export interface FieldDefinition {
  key: string;
  label: string;
  description: string;
  required: boolean;
  aliases: string[];
}

export const CANONICAL_FIELDS: FieldDefinition[] = [
  {
    key: "invoiceNumber",
    label: "Invoice Number",
    description: "Unique invoice or bill reference number",
    required: true,
    aliases: [
      "invoice_number",
      "invoice_no",
      "invoice_id",
      "order_id",
      "sub_order_num",
      "sub_order_no",
      "bill_no",
      "order_no",
    ],
  },
  {
    key: "invoiceDate",
    label: "Invoice Date",
    description: "Invoice or order date (DD-MM-YYYY or YYYY-MM-DD)",
    required: true,
    aliases: ["invoice_date", "order_date", "bill_date", "date"],
  },
  {
    key: "buyerGstin",
    label: "Buyer GSTIN",
    description: "Customer or business 15-character GSTIN number",
    required: false,
    aliases: [
      "buyer_gstin",
      "customer_gstin",
      "party_gstin",
      "customer_bill_to_gstid",
      "customer_ship_to_gstid",
    ],
  },
  {
    key: "buyerName",
    label: "Buyer / Customer Name",
    description: "Recipient customer or entity name",
    required: false,
    aliases: [
      "buyer_name",
      "customer_name",
      "party_name",
      "ship_to_name",
      "reseller_name",
      "buyer",
      "customer",
    ],
  },
  {
    key: "placeOfSupply",
    label: "Place of Supply (State)",
    description: "2-digit state code or state name e.g. '27' or 'Maharashtra'",
    required: true,
    aliases: [
      "place_of_supply",
      "ship_to_state",
      "delivery_state",
      "customer_state",
      "end_customer_state_new",
      "end_customer_state",
      "state",
      "pos",
    ],
  },
  {
    key: "hsnCode",
    label: "HSN / SAC Code",
    description: "4, 6, or 8-digit HSN or SAC code",
    required: false,
    aliases: ["hsn", "hsn_code", "hsn_sac"],
  },
  {
    key: "itemDescription",
    label: "Item Description",
    description: "Product or service description reported alongside the HSN code",
    required: false,
    aliases: [
      "description",
      "item_description",
      "product_description",
      "product_name",
      "item_name",
      "sku_name",
      "title",
    ],
  },
  {
    key: "uqc",
    label: "Unit (UQC)",
    description: "Unit quantity code for the HSN summary e.g. 'PCS', 'KGS'",
    required: false,
    aliases: ["uqc", "unit", "uom", "unit_of_measure", "unit_of_measurement"],
  },
  {
    key: "quantity",
    label: "Quantity",
    description: "Item quantity or unit count",
    required: false,
    aliases: ["quantity", "qty", "units"],
  },
  {
    key: "taxableValue",
    label: "Taxable Value",
    description: "Taxable amount before GST tax calculation",
    required: true,
    aliases: [
      "taxable_value",
      "taxable_amount",
      "taxable_return",
      "total_taxable_sale_value",
      "tax_exclusive_gross",
      "item_subtotal",
      "subtotal",
      "supplier_discounted_price",
      "base_amount",
    ],
  },
  {
    key: "igstAmount",
    label: "IGST Amount",
    description: "Integrated GST amount for inter-state sales",
    required: false,
    aliases: [
      "igst_amount",
      "igst_tax",
      "total_tax_amount",
      "total_tax",
      "tax_amount",
      "gst_amount",
      "gst_return",
      "igst",
    ],
  },
  {
    key: "igstRate",
    label: "IGST / GST Rate",
    description: "IGST or total GST rate percentage",
    required: false,
    aliases: ["igst_rate", "gst_rate", "tax_rate", "gst_percent", "gst", "rate", "tax_percent"],
  },
  {
    key: "cgstRate",
    label: "CGST Rate",
    description: "CGST rate percentage",
    required: false,
    aliases: ["cgst_rate"],
  },
  {
    key: "sgstRate",
    label: "SGST Rate",
    description: "SGST rate percentage",
    required: false,
    aliases: ["sgst_rate"],
  },
  {
    key: "cgstAmount",
    label: "CGST Amount",
    description: "Central GST amount for intra-state sales",
    required: false,
    aliases: ["cgst_amount", "cgst_tax", "cgst"],
  },
  {
    key: "sgstAmount",
    label: "SGST Amount",
    description: "State GST amount for intra-state sales",
    required: false,
    aliases: ["sgst_amount", "sgst_tax", "sgst"],
  },
  {
    key: "totalValue",
    label: "Total Invoice Amount",
    description: "Total invoice value including tax",
    required: false,
    aliases: [
      "total_amount",
      "invoice_amount",
      "total_invoice_value",
      "grand_total",
      "order_total",
      "total",
    ],
  },
  {
    key: "originalInvoiceNumber",
    label: "Original Invoice # (For Returns)",
    description: "Original invoice number referenced by credit note or sales return",
    required: false,
    aliases: [
      "original_invoice_number",
      "original_invoice_no",
      "original_invoice",
      "ref_invoice_no",
      "against_invoice_no",
    ],
  },
  {
    key: "ecoGstin",
    label: "E-Commerce Operator GSTIN",
    description: "GSTIN of the marketplace that collected TCS — drives GSTR-1 Table 14(a)",
    required: false,
    aliases: [
      "eco_gstin",
      "eco_tcs_gstin",
      "ecommerce_gstin",
      "e_commerce_gstin",
      "tcs_gstin",
      "operator_gstin",
      "marketplace_gstin",
    ],
  },
  {
    key: "ecoName",
    label: "E-Commerce Operator Name",
    description: "Legal name of the marketplace collecting TCS",
    required: false,
    aliases: [
      "eco_name",
      "ecommerce_name",
      "operator_name",
      "marketplace_name",
      "eco_company_name",
    ],
  },
];

export type ColumnMappingDict = Record<string, string>; // canonicalKey -> rawHeaderName
